name: CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Setup php version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install PHP Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install Node Dependencies
        run: npm install

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        run: php artisan test

      - name: Set production environment variables
        run: |
          sed -i "s|^APP_NAME=.*|APP_NAME=WeCare|" .env
          sed -i "s|^APP_URL=.*|APP_URL=https://wecare.mustaphahammouny.com|" .env
          sed -i "s|^DB_CONNECTION=.*|DB_CONNECTION=mysql|" .env
          sed -i "s|^DB_DATABASE=.*|DB_DATABASE=${{ secrets.HOSTINGER_DB_DATABASE }}|" .env
          sed -i "s|^DB_USERNAME=.*|DB_USERNAME=${{ secrets.HOSTINGER_DB_USERNAME }}|" .env
          sed -i "s|^DB_PASSWORD=.*|DB_PASSWORD=\"${{ secrets.HOSTINGER_DB_PASSWORD }}\"|" .env
          sed -i "s|^MAIL_MAILER=.*|MAIL_MAILER=smtp|" .env
          sed -i "s|^MAIL_HOST=.*|MAIL_HOST=smtp.hostinger.com|" .env
          sed -i "s|^MAIL_PORT=.*|MAIL_PORT=587|" .env
          sed -i "s|^MAIL_USERNAME=.*|MAIL_USERNAME=support@mustaphahammouny.com|" .env
          sed -i "s|^MAIL_PASSWORD=.*|MAIL_PASSWORD=${{ secrets.HOSTINGER_SMTP_PASSWORD }}|" .env
          sed -i "s|^MAIL_ENCRYPTION=.*|MAIL_ENCRYPTION=TLS|" .env
          sed -i "s|^MAIL_FROM_ADDRESS=.*|MAIL_FROM_ADDRESS=support@mustaphahammouny.com|" .env

      - name: Build assets
        run: npm run build

      - name: Deploy
        if: ${{ success() }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          port: ${{ secrets.HOSTINGER_PORT }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          source: .
          target: /home/${{ secrets.HOSTINGER_USERNAME }}/domains/mustaphahammouny.com/public_html/wecare

      - name: Post deploy
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          port: ${{ secrets.HOSTINGER_PORT }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.HOSTINGER_USERNAME }}/domains/mustaphahammouny.com/public_html/wecare
            php artisan migrate:fresh --seed
            php artisan route:clear
            php artisan optimize
            php artisan storage:link
